export default {
    "prefix": "",
    "suffix": "",
    "<blue>": [],
    "<lightblue>": [],
    "<gray>": [],
    "<green>": [],
    "<purple>": [],
    "<red>": [],
    "<white>": [],
    "<yellow>": [],
    "<number>": [],
    "<escape>": [],
    "<string>": [],
    "<enum>": [],
    "<struct>": [],
}
