export default {
    "prefix": "source.js",
    "suffix": "",
    "<blue>": [
        "keyword.control",
        "storage.type",
        "keyword.operator.expression",
        "keyword.operator.new",
        "constant.language",
        "storage.modifier",
        "keyword.operator.expression.delete",
        "support.type.primitive",
        "support.type.builtin",
        "variable.language",
    ],
    "<lightblue>": [
        "meta.object-literal.key string.quoted.double",
        "meta.object-literal.key",
    ],
    "<gray>": [
        "punctuation.definition.template-expression",
        "comment.block.documentation",
        "storage.type.classdoc",
        "punctuation.separator",
        "keyword.operator",
        "punctuation.accessor",
    ],
    "<green>": [
        "entity.name.type",
        "entity.other.inherited-class",
        "support.class.builtin",
    ],
    "<purple>": [
        "support.type.object.module",
        "keyword.control.default",
        "keyword.control.export",
        // Regex
        "string.regexp",
        "meta.group.regexp",
        "constant.character.escape.backslash.regexp",
        "keyword.control.anchor.regexp",
        "keyword.operator.quantifier.regexp",
        "keyword.operator.negation.regexp",
    ],
    "<red>": [
        "storage.type.function",
        "variable.language.super",
    ],
    "<white>": [
        "meta.brace.square",
        "meta.template.expression",
        "variable.other.readwrite.alias",
        "!variable.other.property.js",
    ],
    "<yellow>": [
        "entity.name.function",
        "punctuation.decorator",
    ],
    "<number>": [],
    "<escape>": [],
    "<string>": [],
    "<enum>": [],
    "<struct>": [],
}
