import { EditorColors } from "./types/EditorColors";

const colors: EditorColors = {
    "actionBar.toggledBackground": "Panel",
    "activityBar.activeBackground": "Transparent",
    "activityBar.activeBorder": "Transparent",
    "activityBar.activeFocusBorder": "Transparent",
    "activityBar.background": "Activity",
    "activityBar.border": "Transparent",
    "activityBar.dropBorder": "Shadow",
    "activityBar.foreground": "Text",
    "activityBar.inactiveForeground": "TextDark",
    "activityBarBadge.background": "Accent",
    "activityBarBadge.foreground": "Main",
    "badge.background": "Input",
    "badge.foreground": "Text",
    "banner.background": "Transparent",
    "banner.foreground": "Accent",
    "banner.iconForeground": "Text",
    "breadcrumb.activeSelectionForeground": "Text",
    "breadcrumb.background": "Main",
    "breadcrumb.focusForeground": "Text",
    "breadcrumb.foreground": "Text",
    "breadcrumbPicker.background": "Panel",
    "button.background": "AccentDark",
    "button.border": "Transparent",
    "button.foreground": "Text",
    "button.hoverBackground": "Input",
    "button.secondaryBackground": "AccentDark",
    "button.secondaryForeground": "Text",
    "button.secondaryHoverBackground": "Input",
    "button.separator": "Seperator",
    "charts.blue": "AnsiBlue",
    "charts.foreground": "Text",
    "charts.green": "AnsiGreen",
    "charts.lines": "Text",
    "charts.orange": "AnsiYellow",
    "charts.purple": "AnsiMagenta",
    "charts.red": "AnsiRed",
    "charts.yellow": "AnsiYellow",
    "chat.requestBorder": "Transparent",
    "chat.slashCommandBackground": "Input",
    "chat.slashCommandForeground": "Text",
    "checkbox.background": "Input",
    "checkbox.border": "Transparent",
    "checkbox.foreground": "Text",
    "checkbox.selectBackground": "Panel",
    "checkbox.selectBorder": "Text",
    "commandCenter.activeBackground": "Input",
    "commandCenter.activeBorder": "Input",
    "commandCenter.activeForeground": "Text",
    "commandCenter.background": "Activity",
    "commandCenter.border": "Input",
    "commandCenter.foreground": "Text",
    "commandCenter.inactiveBorder": "Input",
    "commandCenter.inactiveForeground": "Text",
    "contrastActiveBorder": "Transparent",
    "contrastBorder": "Transparent",
    "debugConsole.errorForeground": "Error",
    "debugConsole.infoForeground": "Info",
    "debugConsole.sourceForeground": "Text",
    "debugConsole.warningForeground": "Warning",
    "debugConsoleInputIcon.foreground": "Text",
    "debugExceptionWidget.background": "Activity",
    "debugExceptionWidget.border": "Input",
    "debugToolBar.border": "Transparent",
    "debugView.exceptionLabelForeground": "Text",
    "debugView.stateLabelForeground": "Text",
    "descriptionForeground": "Text",
    "diffEditor.border": "Input",
    "diffEditor.diagonalFill": "TextDark",
    "diffEditor.insertedLineBackground": "Transparent",
    "diffEditor.insertedTextBackground": "Inserted",
    "diffEditor.insertedTextBorder": "Transparent",
    "diffEditor.move.border": "Transparent",
    "diffEditor.moveActive.border": "Transparent",
    "diffEditor.removedLineBackground": "Transparent",
    "diffEditor.removedTextBackground": "Removed",
    "diffEditor.removedTextBorder": "Transparent",
    "diffEditor.unchangedCodeBackground": "Transparent",
    "diffEditor.unchangedRegionBackground": "Transparent",
    "diffEditor.unchangedRegionForeground": "Transparent",
    "diffEditorGutter.insertedLineBackground": "Inserted",
    "diffEditorGutter.removedLineBackground": "Removed",
    "diffEditorOverview.insertedForeground": "Inserted",
    "diffEditorOverview.removedForeground": "Removed",
    "dropdown.background": "Input",
    "dropdown.border": "Input",
    "dropdown.foreground": "Text",
    "dropdown.listBackground": "Input",
    "editor.background": "Main",
    "editor.findMatchBorder": "Transparent",
    "editor.findMatchHighlightBackground": "Transparent",
    "editor.findMatchHighlightBorder": "Accent",
    "editor.findRangeHighlightBorder": "Transparent",
    "editor.foreground": "Text",
    "editor.inactiveSelectionBackground": "Selection",
    "editor.lineHighlightBackground": "Transparent",
    "editor.lineHighlightBorder": "Transparent",
    "editor.linkedEditingBackground": "Highlight",
    "editor.rangeHighlightBorder": "Transparent",
    "editor.selectionBackground": "Selection",
    "editor.selectionForeground": "Text",
    "editor.selectionHighlightBackground": "Transparent",
    "editor.selectionHighlightBorder": "Transparent",
    "editor.snippetFinalTabstopHighlightBackground": "Transparent",
    "editor.snippetFinalTabstopHighlightBorder": "Transparent",
    "editor.snippetTabstopHighlightBorder": "Transparent",
    "editor.symbolHighlightBackground": "Transparent",
    "editor.symbolHighlightBorder": "Transparent",
    "editor.wordHighlightBackground": "Transparent",
    "editor.wordHighlightBorder": "Transparent",
    "editor.wordHighlightStrongBackground": "Transparent",
    "editor.wordHighlightStrongBorder": "Transparent",
    "editor.wordHighlightTextBackground": "Transparent",
    "editor.wordHighlightTextBorder": "Transparent",
    "editorBracketMatch.border": "Transparent",
    "editorBracketHighlight.foreground1": "Text",
    "editorBracketHighlight.foreground2": "AnsiBlue",
    "editorBracketHighlight.foreground3": "Test",
    "editorBracketHighlight.foreground4": "Test",
    "editorBracketHighlight.foreground5": "Test",
    "editorBracketHighlight.foreground6": "Test",
    "editorBracketPairGuide.activeBackground1": "Accent",
    "editorBracketPairGuide.activeBackground2": "Accent",
    "editorBracketPairGuide.activeBackground3": "Accent",
    "editorBracketPairGuide.activeBackground4": "Accent",
    "editorBracketPairGuide.activeBackground5": "Accent",
    "editorBracketPairGuide.activeBackground6": "Accent",
    "editorBracketPairGuide.background1": "Transparent",
    "editorBracketPairGuide.background2": "Transparent",
    "editorBracketPairGuide.background3": "Transparent",
    "editorBracketPairGuide.background4": "Transparent",
    "editorBracketPairGuide.background5": "Transparent",
    "editorBracketPairGuide.background6": "Transparent",
    "editorCommentsWidget.rangeActiveBackground": "Transparent",
    "editorCommentsWidget.rangeBackground": "Transparent",
    "editorCommentsWidget.resolvedBorder": "Transparent",
    "editorCommentsWidget.unresolvedBorder": "Transparent",
    "editorCursor.foreground": "Text",
    "editorError.background": "Transparent",
    "editorError.border": "Transparent",
    "editorGhostText.background": "Transparent",
    "editorGhostText.border": "Transparent",
    "editorGroup.border": "Input",
    "editorGroup.dropIntoPromptBackground": "Panel",
    "editorGroup.dropIntoPromptBorder": "Transparent",
    "editorGroup.dropIntoPromptForeground": "Text",
    "editorGroup.focusedEmptyBorder": "Transparent",
    "editorGroupHeader.border": "Transparent",
    "editorGroupHeader.noTabsBackground": "Main",
    "editorGroupHeader.tabsBackground": "Panel",
    "editorGroupHeader.tabsBorder": "Transparent",
    "editorGutter.background": "Main",
    "editorGutter.commentGlyphForeground": "Text",
    "editorGutter.commentRangeForeground": "Activity",
    "editorGutter.commentUnresolvedGlyphForeground": "Text",
    "editorGutter.foldingControlForeground": "Text",
    "editorHint.border": "Transparent",
    "editorHoverWidget.background": "Panel",
    "editorHoverWidget.border": "Input",
    "editorHoverWidget.foreground": "Text",
    "editorHoverWidget.highlightForeground": "Accent",
    "editorIndentGuide.activeBackground1": "IndentActive",
    "editorIndentGuide.activeBackground2": "IndentActive",
    "editorIndentGuide.activeBackground3": "IndentActive",
    "editorIndentGuide.activeBackground4": "IndentActive",
    "editorIndentGuide.activeBackground5": "IndentActive",
    "editorIndentGuide.activeBackground6": "IndentActive",
    "editorIndentGuide.background1": "IndentInactive",
    "editorIndentGuide.background2": "IndentInactive",
    "editorIndentGuide.background3": "IndentInactive",
    "editorIndentGuide.background4": "IndentInactive",
    "editorIndentGuide.background5": "IndentInactive",
    "editorIndentGuide.background6": "IndentInactive",
    "editorInfo.background": "Transparent",
    "editorInfo.border": "Transparent",
    "editorInfo.foreground": "Info",
    "editorInlayHint.background": "Transparent",
    "editorInlayHint.foreground": "Text",
    "editorInlayHint.parameterBackground": "Transparent",
    "editorInlayHint.parameterForeground": "Text",
    "editorInlayHint.typeBackground": "Transparent",
    "editorLineNumber.activeForeground": "Accent",
    "editorLineNumber.dimmedForeground": "TextDark",
    "editorLineNumber.foreground": "TextDark",
    "editorLink.activeForeground": "Accent",
    "editorMarkerNavigation.background": "Main",
    "editorOverviewRuler.background": "Panel",
    "editorOverviewRuler.border": "Input",
    "editorOverviewRuler.commentForeground": "Activity",
    "editorOverviewRuler.commentUnresolvedForeground": "Activity",
    "editorOverviewRuler.infoForeground": "Info",
    "editorPane.background": "Main",
    "editorStickyScroll.background": "Main",
    "editorStickyScrollHover.background": "Panel",
    "editorSuggestWidget.background": "Activity",
    "editorSuggestWidget.border": "Transparent",
    "editorSuggestWidget.focusHighlightForeground": "Text",
    "editorSuggestWidget.foreground": "Text",
    "editorSuggestWidget.highlightForeground": "Accent",
    "editorSuggestWidget.selectedForeground": "Accent",
    "editorSuggestWidgetStatus.foreground": "Text",
    "editorUnicodeHighlight.border": "Transparent",
    "editorUnnecessaryCode.border": "Transparent",
    "editorWarning.background": "Warning",
    "editorWarning.border": "Transparent",
    "editorWidget.background": "Panel",
    "editorWidget.border": "Transparent",
    "editorWidget.foreground": "Text",
    "editorWidget.resizeBorder": "Transparent",
    "extensionBadge.remoteBackground": "Accent",
    "extensionBadge.remoteForeground": "Main",
    "extensionButton.background": "Button",
    "extensionButton.foreground": "Text",
    "extensionButton.hoverBackground": "ButtonHover",
    "extensionButton.prominentBackground": "Panel",
    "extensionButton.prominentForeground": "Text",
    "extensionButton.prominentHoverBackground": "Activity",
    "extensionButton.separator": "Seperator",
    "extensionIcon.verifiedForeground": "Accent",
    "focusBorder": "Transparent",
    "foreground": "Text",
    "gitDecoration.addedResourceForeground": "Text",
    "gitDecoration.conflictingResourceForeground": "Text",
    "gitDecoration.deletedResourceForeground": "Text",
    "gitDecoration.ignoredResourceForeground": "Text",
    "gitDecoration.modifiedResourceForeground": "Text",
    "gitDecoration.renamedResourceForeground": "Text",
    "gitDecoration.stageDeletedResourceForeground": "Text",
    "gitDecoration.stageModifiedResourceForeground": "Text",
    "gitDecoration.submoduleResourceForeground": "Text",
    "gitDecoration.untrackedResourceForeground": "Text",
    "icon.foreground": "Text",
    "inlineChat.background": "Panel",
    "inlineChat.border": "Transparent",
    "inlineChat.regionHighlight": "AccentDark",
    "inlineChat.shadow": "Shadow",
    "inlineChatInput.background": "Panel",
    "inlineChatInput.border": "Transparent",
    "inlineChatInput.focusBorder": "Transparent",
    "inlineChatInput.placeholderForeground": "TextPlaceholder",
    "input.background": "Input",
    "input.border": "Input",
    "input.foreground": "Text",
    "input.placeholderForeground": "TextPlaceholder",
    "inputOption.activeBackground": "Input",
    "inputOption.activeBorder": "Transparent",
    "inputOption.activeForeground": "Text",
    "inputValidation.errorBorder": "Transparent",
    "inputValidation.infoBackground": "Activity",
    "inputValidation.infoBorder": "Transparent",
    "inputValidation.warningBorder": "Transparent",
    "interactive.activeCodeBorder": "Input",
    "interactive.inactiveCodeBorder": "Activity",
    "keybindingLabel.border": "Transparent",
    "keybindingLabel.bottomBorder": "Transparent",
    "keybindingTable.headerBackground": "Panel",
    "keybindingTable.rowsBackground": "Panel",
    "listFilterWidget.background": "Panel",
    "listFilterWidget.outline": "Transparent",
    "listFilterWidget.shadow": "Shadow",
    "markdown.extension.editor.codeSpan.background": "Activity",
    "markdown.extension.editor.codeSpan.border": "Transparent",
    "menu.background": "Panel",
    "menu.border": "Panel",
    "menu.foreground": "Text",
    "menu.selectionBackground": "Selection",
    "menu.selectionBorder": "Transparent",
    "menu.selectionForeground": "Accent",
    "menu.separatorBackground": "Input",
    "menubar.selectionBackground": "Input",
    "menubar.selectionBorder": "Transparent",
    "menubar.selectionForeground": "Accent",
    "merge.border": "Transparent",
    "minimap.errorHighlight": "Error",
    "minimap.findMatchHighlight": "AccentDark",
    "minimap.foregroundOpacity": "Transparent",
    "minimap.selectionHighlight": "Accent",
    "minimap.selectionOccurrenceHighlight": "Accent",
    "minimap.warningHighlight": "Warning",
    "notificationCenter.border": "Transparent",
    "notificationCenterHeader.background": "Activity",
    "notificationLink.foreground": "Accent",
    "notifications.background": "Panel",
    "notifications.border": "Transparent",
    "notifications.foreground": "Text",
    "notificationsErrorIcon.foreground": "Error",
    "notificationsInfoIcon.foreground": "Info",
    "notificationsWarningIcon.foreground": "Warning",
    "notificationToast.border": "Transparent",
    "panel.background": "Panel",
    "panel.border": "Border",
    "panel.dropBorder": "Transparent",
    "panelInput.border": "Transparent",
    "panelSection.border": "Transparent",
    "panelSectionHeader.background": "Transparent",
    "panelSectionHeader.border": "Transparent",
    "panelTitle.activeBorder": "Text",
    "panelTitle.activeForeground": "Text",
    "panelTitle.inactiveForeground": "TextDark",
    "peekView.border": "Input",
    "peekViewEditor.background": "Transparent",
    "peekViewEditorGutter.background": "Transparent",
    "peekViewEditorStickyScroll.background": "Transparent",
    "peekViewResult.background": "Panel",
    "peekViewTitle.background": "Panel",
    "pickerGroup.border": "Input",
    "pickerGroup.foreground": "Accent",
    "ports.iconRunningProcessForeground": "Activity",
    "problemsInfoIcon.foreground": "Info",
    "quickInput.background": "Panel",
    "quickInput.foreground": "Text",
    "quickInputList.focusForeground": "Accent",
    "quickInputTitle.background": "Panel",
    "sash.hoverBorder": "Transparent",
    "scm.providerBorder": "Transparent",
    "scrollbar.shadow": "Shadow",
    // Scrollbars / slider
    "scrollbarSlider.activeBackground": "Scrollbar",
    "scrollbarSlider.background": "Scrollbar",
    "scrollbarSlider.hoverBackground": "ScrollbarHover",
    "minimapSlider.activeBackground": "Scrollbar",
    "minimapSlider.background": "Scrollbar",
    "minimapSlider.hoverBackground": "ScrollbarHover",
    "notebookScrollbarSlider.activeBackground": "Scrollbar",
    "notebookScrollbarSlider.background": "Scrollbar",
    "notebookScrollbarSlider.hoverBackground": "ScrollbarHover",
    //
    "search.resultsInfoForeground": "Text",
    "searchEditor.findMatchBorder": "Transparent",
    "searchEditor.textInputBorder": "Transparent",
    "settings.checkboxBackground": "Input",
    "settings.checkboxBorder": "Transparent",
    "settings.checkboxForeground": "Text",
    "settings.dropdownBackground": "Input",
    "settings.dropdownBorder": "Transparent",
    "settings.dropdownForeground": "Text",
    "settings.dropdownListBorder": "Transparent",
    "settings.focusedRowBackground": "Activity",
    "settings.focusedRowBorder": "Transparent",
    "settings.headerBorder": "Transparent",
    "settings.headerForeground": "Accent",
    "settings.modifiedItemIndicator": "AccentDark",
    "settings.numberInputBackground": "Input",
    "settings.numberInputBorder": "Transparent",
    "settings.numberInputForeground": "Text",
    "settings.rowHoverBackground": "Activity",
    "settings.sashBorder": "Transparent",
    "settings.textInputBackground": "Input",
    "settings.textInputBorder": "Transparent",
    "settings.textInputForeground": "Text",
    "sideBar.background": "Panel",
    "sideBar.border": "Border",
    "sideBar.dropBackground": "TextDark",
    "sideBar.foreground": "Text",
    "sideBarSectionHeader.background": "Panel",
    "sideBarSectionHeader.border": "Border",
    "sideBarSectionHeader.foreground": "Accent",
    "sideBarTitle.foreground": "Accent",
    "sideBySideEditor.horizontalBorder": "Input",
    "sideBySideEditor.verticalBorder": "Input",
    "statusBar.background": "Activity",
    "statusBar.border": "Transparent",
    "statusBar.debuggingBackground": "Activity",
    "statusBar.debuggingBorder": "Transparent",
    "statusBar.debuggingForeground": "Text",
    "statusBar.focusBorder": "Activity",
    "statusBar.foreground": "Text",
    "statusBar.noFolderBackground": "Activity",
    "statusBar.noFolderBorder": "Transparent",
    "statusBar.noFolderForeground": "Text",
    "statusBarItem.activeBackground": "Input",
    "statusBarItem.compactHoverBackground": "Input",
    "statusBarItem.errorForeground": "Text",
    "statusBarItem.errorHoverBackground": "Input",
    "statusBarItem.errorHoverForeground": "Text",
    "statusBarItem.focusBorder": "Transparent",
    "statusBarItem.hoverBackground": "Input",
    "statusBarItem.offlineForeground": "Main",
    "statusBarItem.offlineHoverBackground": "Input",
    "statusBarItem.remoteBackground": "Input",
    "statusBarItem.remoteForeground": "Main",
    "statusBarItem.remoteHoverBackground": "Input",
    "statusBarItem.warningHoverBackground": "Input",
    "symbolIcon.arrayForeground": "Text",
    "symbolIcon.booleanForeground": "Text",
    "symbolIcon.colorForeground": "Text",
    "symbolIcon.constantForeground": "Text",
    "symbolIcon.fileForeground": "Text",
    "symbolIcon.folderForeground": "Text",
    "symbolIcon.keyForeground": "Text",
    "symbolIcon.keywordForeground": "Text",
    "symbolIcon.moduleForeground": "Text",
    "symbolIcon.namespaceForeground": "Text",
    "symbolIcon.numberForeground": "Text",
    "symbolIcon.objectForeground": "Text",
    "symbolIcon.operatorForeground": "Text",
    "symbolIcon.packageForeground": "Text",
    "symbolIcon.propertyForeground": "Text",
    "symbolIcon.referenceForeground": "Text",
    "symbolIcon.snippetForeground": "Text",
    "symbolIcon.stringForeground": "Text",
    "symbolIcon.structForeground": "Text",
    "symbolIcon.textForeground": "Text",
    "symbolIcon.typeParameterForeground": "Text",
    "symbolIcon.unitForeground": "Text",
    "tab.activeBackground": "Main",
    "tab.activeBorder": "Transparent",
    "tab.activeBorderTop": "Transparent",
    "tab.activeForeground": "Accent",
    "tab.activeModifiedBorder": "Transparent",
    "tab.border": "Main",
    "tab.hoverBackground": "Activity",
    "tab.hoverBorder": "Transparent",
    "tab.hoverForeground": "Accent",
    "tab.inactiveBackground": "Panel",
    "tab.inactiveForeground": "Text",
    "tab.inactiveModifiedBorder": "Transparent",
    "tab.lastPinnedBorder": "Transparent",
    "tab.unfocusedActiveBackground": "Main",
    "tab.unfocusedActiveBorder": "Transparent",
    "tab.unfocusedActiveBorderTop": "Transparent",
    "tab.unfocusedActiveForeground": "Text",
    "tab.unfocusedActiveModifiedBorder": "Transparent",
    "tab.unfocusedHoverBackground": "Activity",
    "tab.unfocusedHoverBorder": "Transparent",
    "tab.unfocusedHoverForeground": "Text",
    "tab.unfocusedInactiveBackground": "Panel",
    "tab.unfocusedInactiveForeground": "Text",
    "tab.unfocusedInactiveModifiedBorder": "Transparent",
    "terminal.ansiBlack": "AnsiBlack",
    "terminal.ansiBlue": "AnsiBlue",
    "terminal.ansiBrightBlack": "AnsiBrightBlack",
    "terminal.ansiBrightBlue": "AnsiBrightBlue",
    "terminal.ansiBrightCyan": "AnsiBrightCyan",
    "terminal.ansiBrightGreen": "AnsiBrightGreen",
    "terminal.ansiBrightMagenta": "AnsiBrightMagenta",
    "terminal.ansiBrightRed": "AnsiBrightRed",
    "terminal.ansiBrightWhite": "AnsiBrightWhite",
    "terminal.ansiBrightYellow": "AnsiBrightYellow",
    "terminal.ansiCyan": "AnsiCyan",
    "terminal.ansiGreen": "AnsiGreen",
    "terminal.ansiMagenta": "AnsiMagenta",
    "terminal.ansiRed": "AnsiRed",
    "terminal.ansiWhite": "AnsiWhite",
    "terminal.ansiYellow": "AnsiYellow",
    "terminal.background": "Panel",
    "terminal.border": "Transparent",
    "terminal.findMatchBorder": "Transparent",
    "terminal.findMatchHighlightBorder": "Transparent",
    "terminal.foreground": "Text",
    "terminal.tab.activeBorder": "Transparent",
    "terminalCursor.foreground": "Text",
    "testing.message.info.decorationForeground": "Text",
    "testing.peekBorder": "Transparent",
    "textBlockQuote.background": "Panel",
    "textBlockQuote.border": "Accent",
    "textCodeBlock.background": "Activity",
    "textLink.activeForeground": "Text",
    "textLink.foreground": "Accent",
    "textPreformat.foreground": "Accent",
    "titleBar.activeBackground": "Activity",
    "titleBar.activeForeground": "Text",
    "titleBar.border": "Transparent",
    "titleBar.inactiveBackground": "Activity",
    "titleBar.inactiveForeground": "TextDark",
    "toolbar.hoverBackground": "Input",
    "toolbar.hoverOutline": "Transparent",
    "tree.inactiveIndentGuidesStroke": "IndentInactive",
    "tree.indentGuidesStroke": "IndentActive",
    "tree.tableColumnsBorder": "Seperator",
    "tree.tableOddRowsBackground": "Panel",
    "walkThrough.embeddedEditorBackground": "Transparent",
    "walkthrough.stepTitle.foreground": "Accent",
    "welcomePage.background": "Main",
    "welcomePage.progress.background": "Input",
    "welcomePage.progress.foreground": "Accent",
    "welcomePage.tileBackground": "Panel",
    "welcomePage.tileBorder": "Border",
    "welcomePage.tileHoverBackground": "Input",
    "widget.shadow": "Shadow",
    "window.activeBorder": "Transparent",
    "window.inactiveBorder": "Transparent",
    // Errorlens
    "errorLens.errorBackground": "Transparent",
    "errorLens.errorBackgroundLight": "ErrorLensError",
    "errorLens.errorForeground": "ErrorLensError",
    "errorLens.errorForegroundLight": "ErrorLensError",
    "errorLens.errorMessageBackground": "Transparent",
    "errorLens.errorRangeBackground": "Transparent",
    "errorLens.hintBackground": "Transparent",
    "errorLens.hintBackgroundLight": "Transparent",
    "errorLens.hintForeground": "ErrorLensHint",
    "errorLens.hintForegroundLight": "ErrorLensHint",
    "errorLens.hintMessageBackground": "ErrorLensHint",
    "errorLens.hintRangeBackground": "ErrorLensHint",
    "errorLens.infoBackground": "Transparent",
    "errorLens.infoBackgroundLight": "ErrorLensInfo",
    "errorLens.infoForeground": "ErrorLensInfo",
    "errorLens.infoForegroundLight": "ErrorLensInfo",
    "errorLens.infoMessageBackground": "ErrorLensInfo",
    "errorLens.infoRangeBackground": "ErrorLensInfo",
    "errorLens.statusBarErrorForeground": "ErrorLensError",
    "errorLens.statusBarHintForeground": "ErrorLensHint",
    "errorLens.statusBarIconErrorForeground": "ErrorLensError",
    "errorLens.statusBarIconWarningForeground": "ErrorLensWarning",
    "errorLens.statusBarInfoForeground": "ErrorLensInfo",
    "errorLens.statusBarWarningForeground": "ErrorLensWarning",
    "errorLens.warningBackground": "Transparent",
    "errorLens.warningBackgroundLight": "Transparent",
    "errorLens.warningForeground": "ErrorLensWarning",
    "errorLens.warningForegroundLight": "ErrorLensWarning",
    "errorLens.warningMessageBackground": "ErrorLensWarning",
    "errorLens.warningRangeBackground": "ErrorLensWarning",
    "editorActiveLineNumber.foreground": "AccentDark",
    "editorIndentGuide.activeBackground": "Accent",
    "editorIndentGuide.background": "Accent",
    "quickInput.list.focusBackground": "Transparent",
    //
    "editorGroup.emptyBackground": "Main",
    "inputValidation.errorForeground": "Error",
    "inputValidation.infoForeground": "Info",
    "inputValidation.warningForeground": "Warning",
    //
    "list.activeSelectionForeground": "?",
    "list.activeSelectionIconForeground": "?",
    "list.filterMatchBorder": "Transparent",
    "list.focusAndSelectionOutline": "Transparent",
    "list.focusHighlightForeground": "Text",
    "list.highlightForeground": "Accent",
    "list.hoverBackground": "Activity",
    "list.hoverForeground": "Accent",
    "list.inactiveSelectionBackground": "Activity",
    "list.inactiveSelectionForeground": "Accent",
    "list.inactiveSelectionIconForeground": "Text",
    "list.activeSelectionBackground": "Selection",
    "list.errorForeground": "Error",
    "list.warningForeground": "Warning",
    //
    "minimap.background": "Transparent",
    "notificationCenterHeader.foreground": "?",
    "panelSectionHeader.foreground": "?",
    "peekViewEditor.matchHighlightBorder": "?",
    "quickInputList.focusIconForeground": "?",
    "symbolIcon.nullForeground": "Text",
    "terminal.selectionForeground": "Selection",
    "terminalCursor.background": "Selection",
    "testing.message.info.lineBackground": "?",
    "widget.border": "?",
    //
    "editorBracketMatch.background": "Selection",
    "editorCodeLens.foreground": "TextDark",
    "editorError.foreground": "Error",
    "editorHint.foreground": "Info",
    "editorWarning.foreground": "Warning",
    "errorForeground": "Error",
    "inputValidation.errorBackground": "Error",
    "inputValidation.warningBackground": "Warning",
    "keybindingLabel.background": "Input",
    "keybindingLabel.foreground": "Text",
    "statusBarItem.hoverForeground": "Accent",
    "terminal.hoverHighlightBackground": "Selection",
    "terminal.inactiveSelectionBackground": "Selection",
    "terminal.selectionBackground": "Selection",
    //notebook
    "notebook.cellBorderColor": "Transparent",
    "notebook.cellEditorBackground": "Main",
    "notebook.cellInsertionIndicator": "Transparent",
    "notebook.editorBackground": "Panel",
    "notebook.focusedCellBorder": "Input",
    "notebook.focusedEditorBorder": "Input",
    "notebook.inactiveFocusedCellBorder": "Input",
    "notebook.inactiveSelectedCellBorder": "Input",
    "notebook.outputContainerBorderColor": "Transparent",
    "notebook.selectedCellBackground": "Main",
    "notebook.selectedCellBorder": "Transparent",
    "notebook.symbolHighlightBackground": "Transparent",
    "notebook.outputContainerBackgroundColor": "Panel",
    "notebook.cellHoverBackground": "Panel",
    "notebook.focusedCellBackground": "Panel",
    "notebook.cellStatusBarItemHoverBackground": "?",
    "notebook.cellToolbarSeparator": "Seperator",

    "notebookEditorOverviewRuler.runningCellForeground": "?",
    "notebookStatusErrorIcon.foreground": "Error",
    "notebookStatusSuccessIcon.foreground": "Text",
    "notebookStatusRunningIcon.foreground": "Info",

    //
    "editorSuggestWidget.selectedIconForeground": "?",
    "list.focusBackground": "?",
    "list.focusForeground": "?",
    "list.inactiveFocusBackground": "?",
    "list.inactiveFocusOutline": "?",
    "list.deemphasizedForeground": "?",
    "list.dropBackground": "?",
    "list.filterMatchBackground": "?",
    "list.focusOutline": "?",
    "list.invalidItemForeground": "?",
    "commentsView.resolvedIcon": "?",
    "commentsView.unresolvedIcon": "?",
    "debugIcon.breakpointCurrentStackframeForeground": "?",
    "debugIcon.breakpointDisabledForeground": "?",
    "debugIcon.breakpointForeground": "?",
    "debugIcon.breakpointStackframeForeground": "?",
    "debugIcon.breakpointUnverifiedForeground": "?",
    "debugIcon.continueForeground": "?",
    "debugIcon.disconnectForeground": "?",
    "debugIcon.pauseForeground": "?",
    "debugIcon.restartForeground": "?",
    "debugIcon.startForeground": "?",
    "debugIcon.stepBackForeground": "?",
    "debugIcon.stepIntoForeground": "?",
    "debugIcon.stepOutForeground": "?",
    "debugIcon.stepOverForeground": "?",
    "debugIcon.stopForeground": "?",
    "debugTokenExpression.boolean": "?",
    "debugTokenExpression.error": "?",
    "debugTokenExpression.name": "?",
    "debugTokenExpression.number": "?",
    "debugTokenExpression.string": "?",
    "debugTokenExpression.value": "?",
    "debugToolBar.background": "?",
    "debugView.exceptionLabelBackground": "?",
    "debugView.stateLabelBackground": "?", // Transparent
    "debugView.valueChangedHighlight": "?",
    "disabledForeground": "?",
    "editor.findMatchBackground": "?",
    "editor.findRangeHighlightBackground": "?", // Transparent
    "editor.focusedStackFrameHighlightBackground": "?", // Transparent
    "editor.foldBackground": "?", // Transparent
    "editor.hoverHighlightBackground": "?", // Transparent
    "editor.inlineValuesBackground": "?", // Transparent
    "editor.inlineValuesForeground": "?", // Transparent
    "editor.rangeHighlightBackground": "?", // Transparent
    "editor.snippetTabstopHighlightBackground": "?", // Transparent
    "editor.stackFrameHighlightBackground": "?", // Transparent
    "editorBracketHighlight.unexpectedBracket.foreground": "Error", // Transparent
    "editorCursor.background": "?",
    "editorGhostText.foreground": "?", // Transparent
    "editorGroup.dropBackground": "?", // Transparent
    "editorGutter.addedBackground": "?",
    "editorGutter.deletedBackground": "?",
    "editorGutter.modifiedBackground": "?",
    "editorHoverWidget.statusBarBackground": "?",
    "editorInlayHint.typeForeground": "?", // Transparent
    "editorLightBulb.foreground": "?",
    "editorLightBulbAutoFix.foreground": "?",
    "editorMarkerNavigationError.background": "?",
    "editorMarkerNavigationError.headerBackground": "?", // Transparent
    "editorMarkerNavigationInfo.background": "?",
    "editorMarkerNavigationInfo.headerBackground": "?", // Transparent
    "editorMarkerNavigationWarning.background": "?",
    "editorMarkerNavigationWarning.headerBackground": "?", // Transparent
    "editorOverviewRuler.addedForeground": "?", // Transparent
    "editorOverviewRuler.bracketMatchForeground": "?",
    "editorOverviewRuler.commonContentForeground": "?", // Transparent
    "editorOverviewRuler.currentContentForeground": "?", // Transparent
    "editorOverviewRuler.deletedForeground": "?", // Transparent
    "editorOverviewRuler.errorForeground": "Error",
    "editorOverviewRuler.findMatchForeground": "Accent", // Transparent
    "editorOverviewRuler.incomingContentForeground": "?", // Transparent
    "editorOverviewRuler.modifiedForeground": "?", // Transparent
    "editorOverviewRuler.rangeHighlightForeground": "?", // Transparent
    "editorOverviewRuler.selectionHighlightForeground": "?", // Transparent
    "editorOverviewRuler.warningForeground": "?",
    "editorOverviewRuler.wordHighlightForeground": "?", // Transparent
    "editorOverviewRuler.wordHighlightStrongForeground": "?", // Transparent
    "editorOverviewRuler.wordHighlightTextForeground": "?", // Transparent
    "editorRuler.foreground": "?",
    "editorSuggestWidget.selectedBackground": "?", // Transparent
    "editorUnicodeHighlight.background": "?", // Transparent
    "editorUnnecessaryCode.opacity": "?", // Transparent
    "editorWhitespace.foreground": "TextDark", // Transparent
    "extensionIcon.preReleaseForeground": "?",
    "extensionIcon.sponsorForeground": "?",
    "extensionIcon.starForeground": "?",
    "inlineChatDiff.inserted": "?", // Transparent
    "inlineChatDiff.removed": "?", // Transparent
    "inputOption.hoverBackground": "?", // Transparent
    "issues.closed": "?",
    "issues.newIssueDecoration": "?", // Transparent
    "issues.open": "?",
    "listFilterWidget.noMatchesOutline": "?",
    "markdown.extension.editor.formattingMark.foreground": "?", // Transparent
    "markdown.extension.editor.trailingSpace.background": "?", // Transparent
    "merge.commonContentBackground": "?", // Transparent
    "merge.commonHeaderBackground": "?", // Transparent
    "merge.currentContentBackground": "?", // Transparent
    "merge.currentHeaderBackground": "?", // Transparent
    "merge.incomingContentBackground": "?", // Transparent
    "merge.incomingHeaderBackground": "?", // Transparent
    "mergeEditor.change.background": "?", // Transparent
    "mergeEditor.change.word.background": "?", // Transparent
    "mergeEditor.changeBase.background": "?",
    "mergeEditor.changeBase.word.background": "?",
    "mergeEditor.conflict.handled.minimapOverViewRuler": "?", // Transparent
    "mergeEditor.conflict.handledFocused.border": "?", // Transparent
    "mergeEditor.conflict.handledUnfocused.border": "?", // Transparent
    "mergeEditor.conflict.input1.background": "?", // Transparent
    "mergeEditor.conflict.input2.background": "?", // Transparent
    "mergeEditor.conflict.unhandled.minimapOverViewRuler": "?",
    "mergeEditor.conflict.unhandledFocused.border": "?",
    "mergeEditor.conflict.unhandledUnfocused.border": "?", // Transparent
    "mergeEditor.conflictingLines.background": "?", // Transparent
    "minimapGutter.addedBackground": "?",
    "minimapGutter.deletedBackground": "?",
    "minimapGutter.modifiedBackground": "?",
    "panelSection.dropBackground": "?", // Transparent
    "peekViewEditor.matchHighlightBackground": "?", // Transparent
    "peekViewResult.fileForeground": "?",
    "peekViewResult.lineForeground": "?",
    "peekViewResult.matchHighlightBackground": "?", // Transparent
    "peekViewResult.selectionBackground": "?", // Transparent
    "peekViewResult.selectionForeground": "?",
    "peekViewTitleDescription.foreground": "?", // Transparent
    "peekViewTitleLabel.foreground": "?",
    "problemsErrorIcon.foreground": "Error",
    "problemsWarningIcon.foreground": "Warning",
    "profileBadge.background": "?",
    "profileBadge.foreground": "?",
    "progressBar.background": "?",
    "pullRequests.closed": "?",
    "pullRequests.draft": "?",
    "pullRequests.merged": "?",
    "pullRequests.notification": "?",
    "pullRequests.open": "?",
    "quickInputList.focusBackground": "?", // Transparent
    "searchEditor.findMatchBackground": "?", // Transparent
    "selection.background": "Selection",
    "settings.settingsHeaderHoverForeground": "?", // Transparent
    "simpleFindWidget.sashBorder": "?",
    "statusBarItem.errorBackground": "Error",
    "statusBarItem.offlineBackground": "Activity",
    "statusBarItem.offlineHoverForeground": "Activity",
    "statusBarItem.prominentBackground": "Activity", // Transparent
    "statusBarItem.prominentForeground": "Activity",
    "statusBarItem.prominentHoverBackground": "Activity", // Transparent
    "statusBarItem.prominentHoverForeground": "Activity",
    "statusBarItem.remoteHoverForeground": "Activity",
    "statusBarItem.warningBackground": "Warning",
    "statusBarItem.warningForeground": "Text",
    "statusBarItem.warningHoverForeground": "Activity",
    "symbolIcon.classForeground": "?",
    "symbolIcon.constructorForeground": "?",
    "symbolIcon.enumeratorForeground": "?",
    "symbolIcon.enumeratorMemberForeground": "?",
    "symbolIcon.eventForeground": "?",
    "symbolIcon.fieldForeground": "?",
    "symbolIcon.functionForeground": "?",
    "symbolIcon.interfaceForeground": "?",
    "symbolIcon.methodForeground": "?",
    "symbolIcon.variableForeground": "?",
    "terminal.dropBackground": "?", // Transparent
    "terminal.findMatchBackground": "?",
    "terminal.findMatchHighlightBackground": "?", // Transparent
    "terminalCommandDecoration.defaultBackground": "?", // Transparent
    "terminalCommandDecoration.errorBackground": "?",
    "terminalCommandDecoration.successBackground": "?",
    "terminalOverviewRuler.cursorForeground": "?", // Transparent
    "terminalOverviewRuler.findMatchForeground": "?", // Transparent
    "testing.iconErrored": "?",
    "testing.iconFailed": "?",
    "testing.iconPassed": "?",
    "testing.iconQueued": "?",
    "testing.iconSkipped": "?",
    "testing.iconUnset": "?",
    "testing.message.error.decorationForeground": "?",
    "testing.message.error.lineBackground": "?", // Transparent
    "testing.peekHeaderBackground": "?", // Transparent
    "testing.runAction": "?",
    "textSeparator.foreground": "?",
    "toolbar.activeBackground": "?",

};

export default colors;
